### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by RaphaelMarinier** [xiandew/KnightErrant#1]
Hi,

I have some interest in using this project for machine learning research purposes. Would it be possible to add a license file so that the license is clear?
The standard practice is to add a LICENSE.txt file at the root of the repository. A permissive license such as MIT's (see [example](https://github.com/hubotio/hubot/blob/master/LICENSE.md)) would be great.
See also github's documentation about licensing: https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

Thanks!

**Comment by xiandew** [comment]
Hi Raphael,
The MIT license has been added.
